name: Build and deploy Python app to Azure Web App - walkhelp-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        working-directory: ./backend
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        working-directory: ./backend
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here (e.g., PyTest)

      - name: Zip artifact for deployment
        working-directory: ./backend
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            backend/release.zip
            !backend/venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: List downloaded files
        run: ls -R

      - name: Unzip artifact for deployment
        run: unzip release.zip -d extr

        
      - name: List extracted files
        run: ls -R extr

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_220950A93A59464CBDF4D0A5CF1330EC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D56F8EFD0AEE41C882CE1957334719E1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7C13FCA915EB4BC2A78E86DAC898273F }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'walkhelp-backend'
          slot-name: 'Production'
          package: extr/
          startup-command: "python -m uvicorn main:app --host 0.0.0.0 --port 8000"
